/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.ginopc.calculator;

/**
 *
 * @author MaurizioAru
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        CalcDisplay.setText("");
        radioON.setSelected(true);
        radioON.setEnabled(false);
    }
    
    /**
     * turn off calculator, disable all buttons
     */
    public void turnOff(){
        CalcDisplay.setEnabled(false);
        
        // numbers
        Num1.setEnabled(false);
        Num2.setEnabled(false);
        Num3.setEnabled(false);
        Num4.setEnabled(false);
        Num5.setEnabled(false);
        Num6.setEnabled(false);
        Num7.setEnabled(false);
        Num8.setEnabled(false);
        Num9.setEnabled(false);
        Num0.setEnabled(false);
        
        OpeDecimal.setEnabled(false);
        DeleteLast.setEnabled(false);
        ClearDisplay.setEnabled(false);
        OpeGetTotal.setEnabled(false);
        
        // operators
        OpePlus.setEnabled(false);
        OpeMinus.setEnabled(false);
        OpeProduct.setEnabled(false);
        OpeDivision.setEnabled(false);

        // change status of radio buttons
        radioON.setEnabled(true);
        radioOFF.setEnabled(false);
    }

    /**
     * turn off calculator, disable all buttons
     */
    public void turnOn(){
        CalcDisplay.setEnabled(true);
        
        // numbers
        Num1.setEnabled(true);
        Num2.setEnabled(true);
        Num3.setEnabled(true);
        Num4.setEnabled(true);
        Num5.setEnabled(true);
        Num6.setEnabled(true);
        Num7.setEnabled(true);
        Num8.setEnabled(true);
        Num9.setEnabled(true);
        Num0.setEnabled(true);
        
        OpeDecimal.setEnabled(true);
        DeleteLast.setEnabled(true);
        ClearDisplay.setEnabled(true);
        OpeGetTotal.setEnabled(true);
        
        // operators
        OpePlus.setEnabled(true);
        OpeMinus.setEnabled(true);
        OpeProduct.setEnabled(true);
        OpeDivision.setEnabled(true);

        // change status of radio buttons
        radioON.setEnabled(false);
        radioOFF.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        CalcDisplay = new javax.swing.JTextField();
        FormTitle = new javax.swing.JLabel();
        radioON = new javax.swing.JRadioButton();
        radioOFF = new javax.swing.JRadioButton();
        DeleteLast = new javax.swing.JButton();
        ClearDisplay = new javax.swing.JButton();
        OpePlus = new javax.swing.JButton();
        Num1 = new javax.swing.JButton();
        Num2 = new javax.swing.JButton();
        Num3 = new javax.swing.JButton();
        OpeMinus = new javax.swing.JButton();
        Num4 = new javax.swing.JButton();
        Num5 = new javax.swing.JButton();
        Num6 = new javax.swing.JButton();
        OpeProduct = new javax.swing.JButton();
        Num7 = new javax.swing.JButton();
        Num8 = new javax.swing.JButton();
        Num9 = new javax.swing.JButton();
        OpeDivision = new javax.swing.JButton();
        Num0 = new javax.swing.JButton();
        OpeDecimal = new javax.swing.JButton();
        OpeGetTotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        CalcDisplay.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        CalcDisplay.setText("jTextField1");

        FormTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FormTitle.setText("CALCULATOR");

        radioGroup.add(radioON);
        radioON.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioON.setText("ON");
        radioON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioONActionPerformed(evt);
            }
        });

        radioGroup.add(radioOFF);
        radioOFF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radioOFF.setText("OFF");
        radioOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOFFActionPerformed(evt);
            }
        });

        DeleteLast.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeleteLast.setText("<--");
        DeleteLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteLastActionPerformed(evt);
            }
        });

        ClearDisplay.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        ClearDisplay.setText("C");
        ClearDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearDisplayActionPerformed(evt);
            }
        });

        OpePlus.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        OpePlus.setText("+");
        OpePlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpePlusActionPerformed(evt);
            }
        });

        Num1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Num1.setText("1");
        Num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num1ActionPerformed(evt);
            }
        });

        Num2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Num2.setText("2");
        Num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num2ActionPerformed(evt);
            }
        });

        Num3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Num3.setText("3");
        Num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num3ActionPerformed(evt);
            }
        });

        OpeMinus.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        OpeMinus.setText("-");
        OpeMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpeMinusActionPerformed(evt);
            }
        });

        Num4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Num4.setText("4");
        Num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num4ActionPerformed(evt);
            }
        });

        Num5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Num5.setText("5");
        Num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num5ActionPerformed(evt);
            }
        });

        Num6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Num6.setText("6");
        Num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num6ActionPerformed(evt);
            }
        });

        OpeProduct.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        OpeProduct.setText("*");
        OpeProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpeProductActionPerformed(evt);
            }
        });

        Num7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Num7.setText("7");
        Num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num7ActionPerformed(evt);
            }
        });

        Num8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Num8.setText("8");
        Num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num8ActionPerformed(evt);
            }
        });

        Num9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Num9.setText("9");
        Num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num9ActionPerformed(evt);
            }
        });

        OpeDivision.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        OpeDivision.setText("/");
        OpeDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpeDivisionActionPerformed(evt);
            }
        });

        Num0.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Num0.setText("0");
        Num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num0ActionPerformed(evt);
            }
        });

        OpeDecimal.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        OpeDecimal.setText(".");
        OpeDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpeDecimalActionPerformed(evt);
            }
        });

        OpeGetTotal.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        OpeGetTotal.setText("=");
        OpeGetTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpeGetTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CalcDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Num7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Num0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Num5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Num8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OpeDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioOFF)
                                    .addComponent(radioON))
                                .addGap(10, 10, 10)
                                .addComponent(DeleteLast, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClearDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Num6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Num9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OpePlus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OpeMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OpeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OpeDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(OpeGetTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CalcDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(radioON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioOFF))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ClearDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(OpePlus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeleteLast, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpeMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpeDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpeDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpeGetTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioONActionPerformed
        turnOn();
    }//GEN-LAST:event_radioONActionPerformed

    private void OpePlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpePlusActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "+");
    }//GEN-LAST:event_OpePlusActionPerformed

    private void Num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num1ActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "1");
    }//GEN-LAST:event_Num1ActionPerformed

    private void Num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num2ActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "2");
    }//GEN-LAST:event_Num2ActionPerformed

    private void Num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num3ActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "3");
    }//GEN-LAST:event_Num3ActionPerformed

    private void OpeMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpeMinusActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "-");
    }//GEN-LAST:event_OpeMinusActionPerformed

    private void Num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num4ActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "4");
    }//GEN-LAST:event_Num4ActionPerformed

    private void Num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num5ActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "5");
    }//GEN-LAST:event_Num5ActionPerformed

    private void Num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num6ActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "6");
    }//GEN-LAST:event_Num6ActionPerformed

    private void OpeProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpeProductActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "*");
    }//GEN-LAST:event_OpeProductActionPerformed

    private void Num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num7ActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "7");
    }//GEN-LAST:event_Num7ActionPerformed

    private void Num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num8ActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "8");
    }//GEN-LAST:event_Num8ActionPerformed

    private void Num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num9ActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "9");
    }//GEN-LAST:event_Num9ActionPerformed

    private void OpeDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpeDivisionActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "/");
    }//GEN-LAST:event_OpeDivisionActionPerformed

    private void Num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num0ActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + "0");
    }//GEN-LAST:event_Num0ActionPerformed

    private void OpeDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpeDecimalActionPerformed
        CalcDisplay.setText(CalcDisplay.getText() + ".");
    }//GEN-LAST:event_OpeDecimalActionPerformed

    private void OpeGetTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpeGetTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpeGetTotalActionPerformed

    private void ClearDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearDisplayActionPerformed
        CalcDisplay.setText("");
    }//GEN-LAST:event_ClearDisplayActionPerformed

    private void DeleteLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteLastActionPerformed
        
        if (CalcDisplay.getText().length() > 0) {
            int size = CalcDisplay.getText().length() - 1 ;
            String value = CalcDisplay.getText().substring(0, size);
            CalcDisplay.setText(value);
        }
    }//GEN-LAST:event_DeleteLastActionPerformed

    private void radioOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOFFActionPerformed
        turnOff();
    }//GEN-LAST:event_radioOFFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CalcDisplay;
    private javax.swing.JButton ClearDisplay;
    private javax.swing.JButton DeleteLast;
    private javax.swing.JLabel FormTitle;
    private javax.swing.JButton Num0;
    private javax.swing.JButton Num1;
    private javax.swing.JButton Num2;
    private javax.swing.JButton Num3;
    private javax.swing.JButton Num4;
    private javax.swing.JButton Num5;
    private javax.swing.JButton Num6;
    private javax.swing.JButton Num7;
    private javax.swing.JButton Num8;
    private javax.swing.JButton Num9;
    private javax.swing.JButton OpeDecimal;
    private javax.swing.JButton OpeDivision;
    private javax.swing.JButton OpeGetTotal;
    private javax.swing.JButton OpeMinus;
    private javax.swing.JButton OpePlus;
    private javax.swing.JButton OpeProduct;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JRadioButton radioOFF;
    private javax.swing.JRadioButton radioON;
    // End of variables declaration//GEN-END:variables
}
